HW Aug16
amank-05/JS-WDIO-2022 pull request #4
Opened 2022-08-16 22:28 UTC by amank-05

2022-08-17 01:45 UTC, deepaktechnosoft requested changes

2022-08-17 01:45 UTC, deepaktechnosoft commented on test/specs/Class 3/Homework1.js
> +            if (keepMeSignedInClickedIsSelected == true) {
Instead , keepMeSignedInClickedIsSelected == true
you could have just use the boolean-variable like:
if (keepMeSignedInClickedIsSelected) {
    // do this
}

2022-08-17 18:47 UTC, amank-05 reviewed
@deepaktechnosoft

2022-08-19 16:22 UTC, deepaktechnosoft approved these changes

2022-08-19 16:22 UTC, merged